site_name: Template example for simple doc generation 

theme: readthedocs

docs_dir: docs/sources

pages:
- Home: index.md
- Displayers:
  - Introduction: displayer/index.md
  - Displayers: displayer/displayers.md
  - Evaluators: evaluation/evaluators.md
  - Generators: generators/generators.md
  - Layers: layers/layers.md
  - Losses: losses/losses.md
  - Networks: networks/networks.md
  - Transformations: transformations/transformations.md
  - Utils: utils/utils.md
