""" 
The script can:

    - log the experiment on comet.ml
    - create a config file locally with the configuration in it
    - create a csv file with the val_loss and train_loss locally
    - save the checkpoints locally
"""
from config_file import TrainingConfiguration
import sys
from os import mkdir, listdir, environ, makedirs
from os.path import join, dirname, isfile, expanduser
from shutil import copyfile
import argparse
import string
import random
import csv

from operator import itemgetter

import keras.backend as K

import tensorflow as tf
try:
    import horovod.keras as hvd
except ImportError:
    print("Failed to import Horovod, skipping the module.")

parser = argparse.ArgumentParser()
parser.add_argument('-c', '--configuration',
                    help="Path to the directory containing the config file to use. The configuration file should be named 'config_file.py' (see the examples in the config folder of the repository).")
parser.add_argument('horovod')
args = parser.parse_args()

if args.horovod == "True":
    args.horovod = True
elif args.horovod == "False":
    args.horovod = False
else:
    raise RuntimeError("Please specify if horovod should be used.")

if args.horovod:
    hvd.init()
    config_tf = tf.ConfigProto()
    config_tf.gpu_options.allow_growth = True
    config_tf.gpu_options.visible_device_list = str(hvd.local_rank())
    K.set_session(tf.Session(config=config_tf))
    verbose = 1 if hvd.rank() == 0 else 0

sys.path.append(args.configuration)
config = TrainingConfiguration()

key = ''.join(random.choice(string.ascii_uppercase +
                            string.ascii_lowercase + string.digits) for _ in range(32))

output_dir = "{}_{}_{}".format(config.workspace, config.project_name, key)

if (args.horovod and hvd.rank() == 0) or (not args.horovod):
    output_dir = join(environ["EXPERIMENTS_OUTPUT_DIRECTORY"], "{}_{}_{}".format(
        config.workspace, config.project_name, key))

    checkpoints_output_dir = join(output_dir, "checkpoints")
    config_output_dir = join(output_dir, "config")
    logs_output_dir = join(output_dir, "logs")

    # We create all the output directories
    makedirs(output_dir, exist_ok=True)
    makedirs(checkpoints_output_dir, exist_ok=True)
    makedirs(config_output_dir, exist_ok=True)
    makedirs(logs_output_dir, exist_ok=True)

directories_dict = {"output": output_dir, "checkpoints_dir": checkpoints_output_dir,
                    "config_dir": config_output_dir, "log_dir": logs_output_dir}

# Prepare the generators
config.prepare_training_generators()

# Loading the model
model = config.network

if args.horovod:
    config.prepare_horovod(hvd)

if (args.horovod and hvd.rank() == 0) or (not args.horovod):
    config.prepare_runtime_checkpoints(directories_dict)

    # Saving the config file.
    copyfile(join(args.restart, "config/saved_config.py"),
             join(config_output_dir, "saved_config.py"))
    copyfile(join(args.restart, "config/saved_config.py"),
             join(config_output_dir, "temp_config.py"))

if config.weights is not None and args.horovod and hvd.rank() == 0 or config.weights is not None and not args.horovod:
    print("Loading weights (by name): {}".format(config.weights))
    model.load_weights(config.weights, by_name=True)

# Compiling the model
model.compile(loss=config.loss,
              optimizer=config.optimizer,
              metrics=config.metrics)

# Fit the model on the batches generated by datagen.flow().
model.fit_generator(config.train_generator,
                    validation_data=config.validation_generator,
                    epochs=config.epochs,
                    steps_per_epoch=config.steps_per_epoch,
                    callbacks=config.callbacks,
                    workers=config.workers,
                    verbose=verbose,
                    validation_steps=config.validation_steps,
                    use_multiprocessing=config.multiprocessing)
